# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Run on pushes to the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, canceling any in-progress deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: Debug - List workspace contents
        run: |
          echo "Listing repository structure..."
          find . -type f | grep -v "node_modules" | sort
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.140.1'
          extended: true
          
      - name: Build
        run: |
          echo "Building with Hugo..."
          hugo --minify
          
          # Create a test file in the output directory
          echo "<html><body><h1>Test Page</h1><p>This is a test page to verify deployment.</p></body></html>" > public/test-page.html
          
          # Add .nojekyll file
          touch public/.nojekyll
          
          # Debug - show output structure
          echo "Generated site structure:"
          find public -type f | grep -E 'ai/worlds-fair|index.html' | sort
          
          # Ensure the AI World's Fair page exists
          if [ -f "public/ai/worlds-fair/index.html" ]; then
            echo "✅ AI World's Fair page exists at /ai/worlds-fair/index.html"
            ls -l public/ai/worlds-fair/index.html
          else
            echo "❌ ERROR: AI World's Fair page missing at /ai/worlds-fair/index.html"
            exit 1
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
